
language: cpp

matrix:
  include:
    - os: linux
      compiler: gcc
      dist: trusty
      env: DIST="trusty"
      sudo: required
      cache: apt
    - os: linux
      compiler: gcc
      dist: precise
      env: DIST="precise"
      cache: apt

before_install:
 - if [[ "$DIST" == "trusty" ]]; then sudo apt-get update -qq ; sudo apt-get purge -qq fglrx sudo apt-get install -qq --install-recommends mesa-utils ; fi
 - if [[ "$DIST" == "precise" ]]; then sudo apt-get update -qq ; sudo apt-get purge -qq fglrx ; sudo apt-get install -qq --install-recommends mesa-utils ; fi

branches:
  only:
    - master

script: ./travis-ci.sh
